from __future__ import annotations

import argparse
import dataclasses
import json
from pathlib import Path
from typing import Any, Callable

from blackbox.core.accounting import ModelUsage
from blackbox.core.approvals import ApprovalRequest
from blackbox.core.results import structured_output
from blackbox.core.serialization import (
    agent_ref_from_dict,
    agent_ref_to_dict,
    agent_session_from_dict,
    agent_session_to_dict,
    artifact_from_dict,
    artifact_ref_from_dict,
    artifact_ref_to_dict,
    artifact_to_dict,
    event_from_dict,
    event_to_dict,
    invocation_ref_from_dict,
    invocation_ref_to_dict,
    run_state_from_dict,
    run_state_to_dict,
    session_ref_from_dict,
    session_ref_to_dict,
)
from blackbox.runtime.config import RuntimeConfig


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixture", required=True, type=Path)
    parser.add_argument("--parent-commit", required=True)
    args = parser.parse_args()
    fixture = json.loads(args.fixture.read_text(encoding="utf-8"))
    if fixture["generated_by"] != "blackbox-ts":
        raise AssertionError("Canonical fixture must be generated by blackbox-ts.")
    if fixture.get("authority") != "typescript":
        raise AssertionError("Expected native TypeScript fixture authority.")

    payloads = project_python_payloads(fixture["payloads"])
    round_trip("event", payloads, event_from_dict, lambda value: event_to_dict(value, keep_raw=True))
    round_trip("run_state", payloads, run_state_from_dict, run_state_to_dict)
    round_trip("agent_ref", payloads, agent_ref_from_dict, agent_ref_to_dict)
    round_trip("session_ref", payloads, session_ref_from_dict, session_ref_to_dict)
    round_trip("invocation_ref", payloads, invocation_ref_from_dict, invocation_ref_to_dict)
    round_trip("session", payloads, agent_session_from_dict, agent_session_to_dict)
    round_trip("artifact_ref", payloads, artifact_ref_from_dict, artifact_ref_to_dict)
    round_trip("artifact", payloads, artifact_from_dict, artifact_to_dict)

    values = fixture["values"]
    approval = ApprovalRequest(**values["approval_request"])
    assert dataclasses.asdict(approval) == values["approval_request"]
    usage = ModelUsage(**values["usage"])
    assert dataclasses.asdict(usage) == values["usage"]
    config_value = values["runtime_config"]
    config = RuntimeConfig.from_mapping(
        {
            "profile_name": config_value["profile_name"],
            "overrides": config_value["overrides"],
        },
        source=config_value["source"],
    )
    assert config.to_kwargs(surface="model") == config_value["kwargs"]
    output_value = values["output_spec"]
    output = structured_output(output_value["schema"], name=output_value.get("name"))
    assert compact(dataclasses.asdict(output)) == output_value
    print(f"Native TypeScript fixture projection accepted by frozen Python reference {args.parent_commit[:12]}.")


def project_python_payloads(native: dict[str, Any]) -> dict[str, Any]:
    """Add Python serialization tags/null defaults only at this optional boundary."""
    payloads = json.loads(json.dumps(native))
    def tagged(value: dict[str, Any], kind: str, optionals: list[str]) -> dict[str, Any]:
        return {"_kind": kind, **{key: None for key in optionals}, **value}
    payloads["event"] = tagged(payloads["event"], "AgentEvent", [
        "run_id", "sequence", "trace_id", "span_id", "parent_span_id", "span_kind",
        "session_id", "provider", "item_id", "provider_trace_id", "provider_span_id",
        "provider_request_id", "raw",
    ])
    state = payloads["run_state"]
    state["provider_state"] = tagged(state["provider_state"], "ProviderState", ["conversation_id", "previous_response_id"])
    state["items"] = [tagged(item, "RunItem", ["status", "parent_id"]) for item in state["items"]]
    payloads["run_state"] = tagged(state, "RunState", ["provider", "model"])
    for name, kind in [("agent_ref", "AgentRef"), ("session_ref", "SessionRef"), ("invocation_ref", "InvocationRef"), ("session", "AgentSession"), ("artifact_ref", "ArtifactRef")]:
        payloads[name] = tagged(payloads[name], kind, [])
    payloads["artifact"] = tagged(payloads["artifact"], "Artifact", ["uri"])
    return payloads


def round_trip(
    name: str,
    payloads: dict[str, Any],
    hydrate: Callable[[dict[str, Any]], Any],
    serialize: Callable[[Any], dict[str, Any]],
) -> None:
    expected = payloads[name]
    actual = serialize(hydrate(expected))
    if actual != expected:
        raise AssertionError(
            f"{name} failed compatibility round-trip:\n"
            f"expected={json.dumps(expected, sort_keys=True)}\n"
            f"actual={json.dumps(actual, sort_keys=True)}"
        )


def compact(value: dict[str, Any]) -> dict[str, Any]:
    return {key: child for key, child in value.items() if child is not None}


if __name__ == "__main__":
    main()
