from __future__ import annotations

import argparse
import dataclasses
import json
from pathlib import Path
from typing import Any, Callable

from blackbox.core.accounting import ModelUsage
from blackbox.core.approvals import ApprovalRequest
from blackbox.core.results import structured_output
from blackbox.core.serialization import (
    agent_ref_from_dict,
    agent_ref_to_dict,
    agent_session_from_dict,
    agent_session_to_dict,
    artifact_from_dict,
    artifact_ref_from_dict,
    artifact_ref_to_dict,
    artifact_to_dict,
    event_from_dict,
    event_to_dict,
    invocation_ref_from_dict,
    invocation_ref_to_dict,
    run_state_from_dict,
    run_state_to_dict,
    session_ref_from_dict,
    session_ref_to_dict,
)
from blackbox.runtime.config import RuntimeConfig


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixture", required=True, type=Path)
    parser.add_argument("--parent-commit", required=True)
    args = parser.parse_args()
    fixture = json.loads(args.fixture.read_text(encoding="utf-8"))
    if fixture["generated_by"] != "blackbox-ts":
        raise AssertionError("Reverse fixture must be generated by blackbox-ts.")
    if fixture["target_parent_commit"] != args.parent_commit:
        raise AssertionError("Reverse fixture targets a different Python parent commit.")

    payloads = fixture["payloads"]
    round_trip("event", payloads, event_from_dict, lambda value: event_to_dict(value, keep_raw=True))
    round_trip("run_state", payloads, run_state_from_dict, run_state_to_dict)
    round_trip("agent_ref", payloads, agent_ref_from_dict, agent_ref_to_dict)
    round_trip("session_ref", payloads, session_ref_from_dict, session_ref_to_dict)
    round_trip("invocation_ref", payloads, invocation_ref_from_dict, invocation_ref_to_dict)
    round_trip("session", payloads, agent_session_from_dict, agent_session_to_dict)
    round_trip("artifact_ref", payloads, artifact_ref_from_dict, artifact_ref_to_dict)
    round_trip("artifact", payloads, artifact_from_dict, artifact_to_dict)

    values = fixture["values"]
    approval = ApprovalRequest(**values["approval_request"])
    assert dataclasses.asdict(approval) == values["approval_request"]
    usage = ModelUsage(**values["usage"])
    assert dataclasses.asdict(usage) == values["usage"]
    config_value = values["runtime_config"]
    config = RuntimeConfig.from_mapping(
        {
            "profile_name": config_value["profile_name"],
            "overrides": config_value["overrides"],
        },
        source=config_value["source"],
    )
    assert config.to_kwargs(surface="model") == config_value["kwargs"]
    output_value = values["output_spec"]
    output = structured_output(output_value["schema"], name=output_value.get("name"))
    assert compact(dataclasses.asdict(output)) == output_value
    print(f"TypeScript reverse fixtures accepted by Python parent {args.parent_commit[:12]}.")


def round_trip(
    name: str,
    payloads: dict[str, Any],
    hydrate: Callable[[dict[str, Any]], Any],
    serialize: Callable[[Any], dict[str, Any]],
) -> None:
    expected = payloads[name]
    actual = serialize(hydrate(expected))
    if actual != expected:
        raise AssertionError(
            f"{name} failed reverse round-trip:\n"
            f"expected={json.dumps(expected, sort_keys=True)}\n"
            f"actual={json.dumps(actual, sort_keys=True)}"
        )


def compact(value: dict[str, Any]) -> dict[str, Any]:
    return {key: child for key, child in value.items() if child is not None}


if __name__ == "__main__":
    main()
